CREATE SEQUENCE IF NOT EXISTS trainee_sequence START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS trainer_sequence START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS training_sequence START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_sequence START WITH 1 INCREMENT BY 1;